---
apiVersion: svc.dpu.nvidia.com/v1alpha1
kind: DPUDeployment
metadata:
  name: hbn-only
  namespace: dpf-operator-system
spec:
  dpus:
    bfb: bf-bundle
    flavor: dpf-provisioning-hbn
    dpuSets:
    - nameSuffix: "dpuset1"
      nodeSelector:
        matchLabels:
          feature.node.kubernetes.io/dpu-enabled: "true"
  services:
    doca-hbn:
      serviceTemplate: doca-hbn
      serviceConfiguration: doca-hbn
  serviceChains:
  - ports:
    - serviceInterface:
        matchLabels:
          uplink: p0
    - service:
        name: doca-hbn
        interface: p0_if
  - ports:
    - serviceInterface:
        matchLabels:
          uplink: p1
    - service:
        name: doca-hbn
        interface: p1_if
  - ports:
    - serviceInterface:
        matchLabels:
          port: host_pf0_rep
    - service:
        name: doca-hbn
        interface: host_pf0_sf
  - ports:
    - serviceInterface:
        matchLabels:
          port: host_pf1_rep
    - service:
        name: doca-hbn
        interface: host_pf1_sf
